# Generated by Django 5.1.15 on 2026-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('trade_license', models.CharField(max_length=50, unique=True)),
                ('vat_number', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Dubai', max_length=80)),
                ('emirate', models.CharField(default='Dubai', max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(max_length=120)),
                ('contact_title', models.CharField(blank=True, max_length=80)),
                ('payment_terms', models.CharField(choices=[('immediate', 'Cash / Immediate'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('lc', 'Letter of Credit')], default='net_30', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
