# Generated by Django 5.1.15 on 2026-08-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True)),
                ('engine_number', models.CharField(max_length=40, unique=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('in_transit', 'In Transit')], db_index=True, default='available', max_length=20)),
                ('warehouse', models.CharField(default='Al Quoz Yard A', max_length=80)),
                ('location_bay', models.CharField(blank=True, max_length=40)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_unit', to='trucks.truck')),
            ],
            options={
                'verbose_name': 'Inventory Unit',
                'verbose_name_plural': 'Inventory Units',
                'ordering': ['warehouse', 'vin'],
            },
        ),
    ]
