# Generated by Django 6.0.7 on 2026-08-01 14:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(max_length=40)),
                ('client_email', models.EmailField(max_length=254)),
                ('subtotal_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_price_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('drive_type', models.CharField(help_text='e.g. 6x4, 8x4, 4x2', max_length=20)),
                ('horsepower', models.PositiveIntegerField()),
                ('emission_standard', models.CharField(max_length=50)),
                ('engine_model', models.CharField(max_length=150)),
                ('transmission', models.CharField(max_length=150)),
                ('specs', models.JSONField(default=dict, help_text='Deep technical specs: axle, cargo, cabin, fuel, safety, etc.')),
                ('fob_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('landed_cost_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retail_price_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_vin_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_selling_price_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custom_notes', models.TextField(blank=True, default='')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trucks.quotation')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='trucks.truck')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
