# Generated by Django 5.1.15 on 2026-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Shacman', 'Shacman'), ('Sinotruk HOWO', 'Sinotruk HOWO'), ('FAW', 'FAW'), ('Dongfeng', 'Dongfeng'), ('Foton', 'Foton'), ('JAC', 'JAC')], db_index=True, max_length=50)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('tipper', 'Tipper'), ('tractor', 'Tractor Head'), ('cargo', 'Cargo Truck'), ('mixer', 'Concrete Mixer'), ('tanker', 'Tanker'), ('flatbed', 'Flatbed')], db_index=True, max_length=20)),
                ('horsepower', models.PositiveIntegerField()),
                ('engine', models.CharField(max_length=120)),
                ('transmission', models.CharField(max_length=80)),
                ('drive_type', models.CharField(help_text='e.g. 6x4, 4x2, 8x4', max_length=20)),
                ('fuel', models.CharField(default='Diesel', max_length=30)),
                ('emission', models.CharField(help_text='e.g. Euro 5, Euro 6', max_length=30)),
                ('cab_type', models.CharField(max_length=80)),
                ('payload_kg', models.PositiveIntegerField(help_text='Payload capacity in kg')),
                ('gross_weight_kg', models.PositiveIntegerField()),
                ('wheelbase_mm', models.PositiveIntegerField()),
                ('dimensions', models.CharField(help_text='L x W x H in mm', max_length=80)),
                ('fuel_tank_l', models.PositiveIntegerField()),
                ('tyre_size', models.CharField(max_length=40)),
                ('vin', models.CharField(db_index=True, max_length=17, unique=True)),
                ('engine_number', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price AED', max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Purchase cost AED', max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('in_transit', 'In Transit')], db_index=True, default='available', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Placeholder image URL')),
                ('description', models.TextField(blank=True)),
                ('warranty', models.CharField(default='12 months / 100,000 km', max_length=120)),
                ('warehouse', models.CharField(default='Al Quoz Yard A', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'model', '-year'],
                'indexes': [models.Index(fields=['brand', 'model'], name='trucks_truc_brand_426c65_idx'), models.Index(fields=['availability', 'category'], name='trucks_truc_availab_ec0553_idx')],
            },
        ),
    ]
